### ISSUE TITLE
Not an issue, simple your opinion on how to improve Joomla! security in the year 2018

### ISSUE THREAD

**Issue by danjde** [rastating/joomlavs#32]
Hi @rastating 
I'm writing to ask if you know that now [VEL](https://vel.joomla.org/) has a [JSON formatted feed available](https://vel.joomla.org/vel-feed) and this should be fine for the creation of a plugin that compare installed extensions/plugins with those reported by VES.

I've open this thread on Joomla! forum: https://forum.joomla.org/viewtopic.php?f=714&t=959786

I'm not a developer I'm a Joomla! user and I think that a similar plugin would increase Joomla! security.

Do you know any Joomla developer interesting on this trip?

PS
Many many thanks for your very useful Joomla! joomlavs!

Ciao!

Davide
Italy

**Comment by rastating** [comment]
Hey @danjde 

I was not aware of the feed! I think it'd be a really good replacement for the existing JoomlaVS feed too; as it will ensure JoomlaVS is getting a community driven feed outside the realms of GitHub. It will require some rework, but I think I'll try and prioritise this over some other projects in the pipeline at the moment :smile: 

In regards to developing a plugin to integrate this within Joomla itself - I agree, I think that would be a very good addition for users to have and I may look into developing one myself, unless anyone else beats me to the finish line :smile:

**Comment by rastating** [comment]
A bit of a deeper look into it, and it looks like the VEL feed unfortunately doesn't contain the package names of the vulnerable components :cry: so there's not much that can be done in way of automation.

Nether the less, it will be a useful feed to monitor for updates to the JoomlaVS library, and I will still look into creating a Joomla plugin to provide similar functionality to that of JoomlaVS :smile:

**Comment by fcoulter** [comment]
The VEL feed DOES contain the package names and other information from the extension installation manifest, check the documentation at : https://vel.joomla.org/vel-feed

install_data: json fomatted installation data from extension installation manifest, including name, type, creationDate, author, authorUrl, copyright, version and group (for plugins). This can be used to distinguish extensions with similar names, note that we don't include the author email 

That is exactly why it is included, so that it can be automatically checked against the Joomla extensions.

**Comment by rastating** [comment]
@fcoulter I was taking a look at sample data last night, and found there was a significant amount that had the `install_data` property missing; out of 300 items, there was only 135 that contained it.

I assumed that maybe this is a new property that's only recently been added, and would be mandatory moving forward, but isn't being added retrospectively. That's why I was planning to use a combination of both the VEL feed and the collection I and a few others have put together (currently, the components file in this repository contains 1,191 vulnerabilities with linked component identifiers).

**Comment by fcoulter** [comment]
Most of the newer items should include it. You are right, the ones where it is missing are mainly older items, because to supply that information means someone (ie me) finding a copy of the extension and uploading its manifest. 

There will always be some that don't because there will be occasions where the VEL don't have access to the extension itself, eg because the vulnerability has been self-reported by the developer, and they don't supply us with a copy. But that should be fairly rare for new items.

**Comment by rastating** [comment]
@fcoulter awesome :smile: 

I know the pain of trying to work with the older vulnerabilities - it took a significant amount of automation just to harvest component names for the database in JoomlaVS; automating retrieving manifests for them would have been near impossible!

It should be a good resource for the community to have; keep up the good work!
