### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by ViktorIwan** [rastating/joomlavs#36]
I'm wondering if there's plan to update the fingerprint list of known joomla issue. I'm not a ruby developer, is there something that i can help ?

**Comment by rastating** [comment]
The fingerprints are stored in the JSON files found in the `data` directory. If you want to add some new ones, it's possible to edit these files rather than writing any new Ruby code.

See this pull request for a few bits of information on the formatting: https://github.com/rastating/joomlavs/pull/29

For vulnerabilities in the core Joomla code, these go in `data/joomla.json`, which is a single array of vulnerability objects, as opposed to an array of extension objects.
